site_name: My Notes

theme:
    name: 'material'

extra:
    search:
        language: 'ja'

extra_css:
    - css/heading.css
    - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
    - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - pymdownx.arithmatex
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
    - toc:
        permalink: False
        separator: "_"
