#!/bin/sh
#
# Called by "git commit" with no arguments. The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

gittop_dir=$(git rev-parse --show-toplevel)
hook_name=$(basename $0)

# Redirect output to stderr.
exec 1>&2

for script in ; do
    echo $script
    hook=${gittop_dir}/scripts/${script}
    for file in $(git diff-index --cached --name-only --diff-filter=ACMR $against)
    do
        $hook $file
        if [ $? != 0 ]; then
            echo "failed: $file"
            exit 1
        fi
    done
done

for script in mkdocs_build.sh check_unstaged_untracked.sh
do
    echo $script
    ${gittop_dir}/scripts/${script}
    if [ $? != 0 ]; then
        exit 1
    fi
done

exit 0
